USE [master]
GO

/****** Drop existing database if it exists ******/
IF EXISTS (SELECT name FROM sys.databases WHERE name = N'MeetingRoom')
BEGIN
    ALTER DATABASE [MeetingRoom] SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE [MeetingRoom];
END
GO

/****** Object:  Database [MeetingRoom]    ******/
CREATE DATABASE [MeetingRoom]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MeetingRoom', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\MeetingRoom.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MeetingRoom_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL17.SQLEXPRESS\MSSQL\DATA\MeetingRoom_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [MeetingRoom] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MeetingRoom].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MeetingRoom] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [MeetingRoom] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [MeetingRoom] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [MeetingRoom] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [MeetingRoom] SET ARITHABORT OFF 
GO
ALTER DATABASE [MeetingRoom] SET AUTO_CLOSE ON 
GO
ALTER DATABASE [MeetingRoom] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [MeetingRoom] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [MeetingRoom] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [MeetingRoom] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [MeetingRoom] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [MeetingRoom] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [MeetingRoom] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [MeetingRoom] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [MeetingRoom] SET  ENABLE_BROKER 
GO
ALTER DATABASE [MeetingRoom] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [MeetingRoom] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [MeetingRoom] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [MeetingRoom] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [MeetingRoom] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [MeetingRoom] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [MeetingRoom] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [MeetingRoom] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [MeetingRoom] SET  MULTI_USER 
GO
ALTER DATABASE [MeetingRoom] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [MeetingRoom] SET DB_CHAINING OFF 
GO
ALTER DATABASE [MeetingRoom] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [MeetingRoom] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [MeetingRoom] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [MeetingRoom] SET QUERY_STORE = OFF
GO

USE [MeetingRoom]
GO


CREATE USER [username] FOR LOGIN [username] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [username]
GO
*/

/****** Object:  Table [dbo].[Room]    ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Room](
	[roomID] [int] IDENTITY(1,1) NOT NULL,
	[roomName] [nvarchar](100) NOT NULL,
	[roomNumber] [char](6) NOT NULL,
	[location] [nvarchar](100) NULL,
	[capacity] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[roomID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[roomNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[User]    ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[User](
	[userID] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NOT NULL,
	[LastName] [nvarchar](50) NOT NULL,
	[personalID] [char](13) NOT NULL,
	[email] [nvarchar](100) NULL,
	[phone] [nvarchar](10) NULL,
	[RegistrationDate] [date] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[userID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[personalID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[email] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Object:  Table [dbo].[Booking]    ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Booking](
	[bookingID] [int] IDENTITY(1,1) NOT NULL,
	[userID] [int] NOT NULL,
	[roomID] [int] NOT NULL,
	[startDateTime] [datetime] NOT NULL,
	[endDateTime] [datetime] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[bookingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

/****** Add Default Constraints ******/
ALTER TABLE [dbo].[User] ADD  DEFAULT (getdate()) FOR [RegistrationDate]
GO

/****** Add Foreign Key Constraints ******/
ALTER TABLE [dbo].[Booking]  WITH CHECK ADD FOREIGN KEY([userID])
REFERENCES [dbo].[User] ([userID])
GO

ALTER TABLE [dbo].[Booking]  WITH CHECK ADD FOREIGN KEY([roomID])
REFERENCES [dbo].[Room] ([roomID])
GO

/****** Add Check Constraints ******/
ALTER TABLE [dbo].[Room]  WITH CHECK ADD CHECK  (([capacity] >= 1 AND [capacity] <= 100))
GO

ALTER TABLE [dbo].[Booking]  WITH CHECK ADD CHECK  (([endDateTime] > [startDateTime]))
GO

USE [master]
GO
ALTER DATABASE [MeetingRoom] SET  READ_WRITE 
GO
